config/urls.py
# flake8: noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings
from mailing import views
from mailing.views import homeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homeView.as_view(), name="home"),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
# flake8: noqa
from django.urls import include, path
from django.views.decorators.cache import cache_page
from . import views
from django.conf import settings
from django.conf.urls.static import static

from mailing.apps import MailingConfig
from mailing.services import block_mailing, run_mail
from mailing.views import (Contacts, MailingAttemptCreateView, MailingAttemptListView, MailingCreateView,
                           MailingDeleteView, MailingDetailView,
                           MailingListView, MailingUpdateView, MessageCreateView, MessageDeleteView,
                           MessageDetailView, MessageListView,
                           MessageUpdateView, ReceiveMailCreateView, ReceiveMailDetailView, ReceiveMailingDeleteView,
                           ReceiveMailListView,
                           ReceiveMailUpdateView, homeView, Messages)

app_name = MailingConfig.name

urlpatterns = [
    path("home/", homeView.as_view(), name="home"),
    path("contacts/", cache_page(60)(Contacts.as_view()), name="contacts"),
    path("message/", Messages.as_view(), name="message"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>/run_mail/", run_mail, name="run_mail"),
    path("mailing/<int:pk>/detail/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/new/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/edit/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("receivemail/", ReceiveMailListView.as_view(), name="receivemail_list"),
    path("receivemail/<int:pk>/detail/", cache_page(60)(ReceiveMailDetailView.as_view()), name="receivemail_detail"),
    path("receivemail/create/", ReceiveMailCreateView.as_view(), name="receivemail_form"),
    path("receivemail/<int:pk>/edit/", ReceiveMailUpdateView.as_view(), name="receivemail_update"),
    path("receivemail/<int:pk>/delete/", ReceiveMailingDeleteView.as_view(), name="receivemail_delete"),
    path("message/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/detail/", MessageDetailView.as_view(), name="message_detail"),
    path("message/new/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/edit/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("send/", MailingAttemptListView.as_view(), name="send_list"),
    path("send/create/", MailingAttemptCreateView.as_view(), name="send_create"),
    path("attempt/", MailingAttemptListView.as_view(), name="attempt"),
    path("block_mailing/<int:pk>", block_mailing, name="block_mailing"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UserListView,
    UserUpdateView,
    email_verification, PasswordRecoveryView, user_logout,
)
# flake8: noqa
app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", user_logout, name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("users/", UserListView.as_view(), name="user_list"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
    path("password-recovery/", PasswordRecoveryView.as_view(), name="password_recovery"),
    # path("attempt/", cache_page(60)(MailingAttemptListView.as_view()), name="attempt"),
]

mailing/models.py
# flake8: noqa
from django.db import models

from users.models import User


class ReceiveMail(models.Model):
    """Модель «Получатель рассылки»:"""

    mail = models.EmailField(max_length=255, verbose_name="Письмо", unique=True)
    fio = models.CharField(max_length=255, verbose_name="ФИО")
    comment = models.TextField(verbose_name="Комментарии", null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name="активность")
    owner = models.ForeignKey(
        User,
        verbose_name="Получатель",
        help_text="укажите получателя рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"{self.fio} {self.mail} "

    class Meta:
        verbose_name = "получатель"
        verbose_name_plural = "получатели"
        ordering = ["fio"]
        permissions = [
            ("can_blocking_client", "Может блокировать получателя"),
        ]


class Message(models.Model):
    """Модель «Сообщение»:"""

    subject = models.CharField(max_length=255, verbose_name="Тема письма")
    content = models.TextField(verbose_name="Содержимое письма")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Владелец")



    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "письмо"
        verbose_name_plural = "письма"
        ordering = ["subject"]
        permissions = [
            ('can_blocking_sms', 'Может блокировать сообщение'),
        ]


class Mailing(models.Model):
    """Модель «Рассылка»:"""

    CREATED = "Создано"
    LAUNCHED = "Запущено"
    FINISHED = "Завершена"

    STATUS_CHOICES = [
        (CREATED, "Создано"),
        (LAUNCHED, "Запущено"),
        (FINISHED, "Завершена"),
    ]

    first_sending = models.DateTimeField(verbose_name="Дата первой отправки", null=True, blank=True)
    end_sending = models.DateTimeField(verbose_name="Дата окончания отправки",null=True, blank=True)

    status = models.CharField(max_length=11, choices=STATUS_CHOICES, default=CREATED, verbose_name="Статус рассылки")
    is_active = models.BooleanField(default=True, verbose_name="активна", null=True, blank=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение", related_name="mailings", null=True, blank=True)
    client = models.ManyToManyField(ReceiveMail, verbose_name="Клиент",)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Владелец")

    def __str__(self):
        return f"{self.id}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["first_sending"]
        permissions = [
            ("set_is_active", "set is active"),
        ]


class AttemptMailing(models.Model):
    """Модель «Попытка рассылки»"""

    date_attempt = models.DateTimeField(verbose_name="Дата и время попытки")
    status = models.CharField(max_length=115, verbose_name="Статус попытки")
    response = models.TextField(verbose_name="Комментарии", null=True, blank=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка", related_name="mailing")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL,  null=True, blank=True, verbose_name="Владелец")
    def __str__(self):
        return f'{self.date_attempt} "{self.status}" '

    class Meta:
        verbose_name = "попытка"
        verbose_name_plural = "попытки"
        ordering = ["date_attempt", "status"]

mailing/forms.py
# flake8: noqa
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm

from .models import AttemptMailing, Mailing, Message, ReceiveMail


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=255, label="Тема письма")
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")
    recipients = forms.CharField(widget=forms.Textarea, label="Получатели (через запятую)")


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        #exclude = ("set_is_active", "owner", "first_sending", "end_sending")


class MessageForm(StyleFormMixin, ModelForm):

    class Meta:

        model = Message
        fields = "__all__"


class ReceiveMailForm(StyleFormMixin, ModelForm):

    class Meta:

        model = ReceiveMail
        fields = "__all__"
        exclude = ("can_blocking_client", "owner")


class ReceiveMailModeratorForm(StyleFormMixin, ModelForm):
    class Meta:

        model = ReceiveMail
        fields = "__all__"


class MailingModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = "__all__"

mailing/views.py
# flake8: noqa
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, request
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from mailing.models import AttemptMailing, Mailing, Message, ReceiveMail

from .forms import MailingForm, MailingModeratorForm, MessageForm, ReceiveMailForm, ReceiveMailModeratorForm
from .services import get_attempt_from_cache, get_mailing_from_cache





# def home(request):
#     return render(request, 'home.html')

def base(request):

    return render(request, "base.html")


# Главная страница
class homeView(TemplateView):
    template_name = "mailing/home.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Главная"
        context_data["count_mailing"] = len(Mailing.objects.all())
        active_mailings_count = Mailing.objects.filter(status="Создано").count()
        context_data["active_mailings_count"] = active_mailings_count
        unique_clients_count = ReceiveMail.objects.distinct().count()
        context_data["unique_clients_count"] = unique_clients_count
        return context_data


# Шаблон контакты
class Contacts(TemplateView):

    template_name = "mailing/contacts.html"

    def contacts(request):
        if request.method == "POST":
            name = request.POST.get("name")  # получаем имя
            message = request.POST.get("message")  # получаем сообщение
            return HttpResponse(f"Спасибо, {name}! {message} Сообщение получено.")
        return render(request, "mailing/contacts.html")


# Страница ответа на отправленное сообщение
class Messages(TemplateView):

    template_name = "mailing/message_list.html"


# CRUD для рассылок
class MailingListView(ListView):
    model = Mailing
    template_name = "mailing/mailing_list.html"

    def get_queryset(self):
        return get_mailing_from_cache()


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        recipient = form.save()
        recipient.owner = self.request.user
        recipient.save()
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/receivemail_list.html"

    def get_queryset(self):
        return get_mailing_from_cache()


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("mailing.set_is_active"):
            return MailingModeratorForm
        return MailingForm


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    template_name = "mailing/mailing_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")


# CRUD для получателей


class ReceiveMailListView(ListView):
    model = ReceiveMail


class ReceiveMailDetailView(LoginRequiredMixin, DetailView):
    model = ReceiveMail
    form_class = ReceiveMailModeratorForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return self.object


class ReceiveMailCreateView(LoginRequiredMixin, CreateView):
    model = ReceiveMail
    form_class = ReceiveMailForm
    template_name = "mailing/receivemail_form.html"
    success_url = reverse_lazy("mailing:receivemail_list")

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()

        return super().form_valid(form)


class ReceiveMailUpdateView(LoginRequiredMixin, UpdateView):
    model = ReceiveMail
    form_class = ReceiveMailForm

    success_url = reverse_lazy("mailing:receivemail_list")

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("mailing.can_blocking_client"):
            return ReceiveMailModeratorForm
        return ReceiveMailForm


class ReceiveMailingDeleteView(LoginRequiredMixin, DeleteView):
    model = ReceiveMail
    template_name = "mailing/receivemail_delete.html"
    success_url = reverse_lazy("mailing:receivemail_list")


# CRUD для сообщений
class MessageListView(ListView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_list.html'

    def get_queryset(self, *args, **kwargs):

        queryset = super().get_queryset()
        print(queryset)  # Для отладки
        return queryset





class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    form_class = MessageForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            raise PermissionDenied
        return self.object


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        recipient = form.save()
        recipient.owner = self.request.user
        recipient.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            raise PermissionDenied
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            raise PermissionDenied
        return self.object


class MailingAttemptCreateView(LoginRequiredMixin, CreateView):
    model = AttemptMailing

    def form_valid(self, form):
        recipient = form.save()
        recipient.owner = self.request.user
        recipient.save()
        return super().form_valid(form)


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = AttemptMailing
    template_name = "mailing/attemptmailing_list.html"

    def get_queryset(self, *args, **kwargs):
        if self.request.user:
            return super().get_queryset()
        elif self.request.user.groups.filter(name="Пользователи").exists():
            return super().get_queryset().filter(owner=self.request.user)
        raise PermissionDenied

mailing/templates/mailing/attemptmailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container marketing mt-5">
    <div class="container text-center mt-3">
        <div class="row justify-content-center">
            <div class="col-4"></div>
            <div class="col-4">
                <h2>Статистика по рассылкам</h2>
            </div>
            <div class="col-4"></div>
        </div>

    </div>
    <div class="row">
        <div class="table-responsive small">
            <table class="table table-success table-striped">
                <thead>
                <tr>
                    <th>Тема сообщения</th>
                    <th>Описание рассылки</th>
                    <th>Дата</th>
                    <th>Статус</th>
                    <th>Ответ сервера</th>
                    {% if user.is_authenticated %}
                    <th>Создал</th>
                    {% endif %}
                </tr>
                </thead>

                {% for object in object_list %}
                <tr>
                    <td>{{ object.mailing.message.subject }}</td>
                    <td>{{ object.mailing.message.content|truncatechars:30 }}</td>
                    <td>{{ object.date_attempt}}</td>
                    <td>{{ object.status}}</td>
                    <td>{{ object.response}}</td>
                    {% if user.is_authenticated %}
                    <td>{{ object.mailing.owner }}</td>
                    {% endif %}

                </tr>
                {% endfor%}
            </table>

        </div><!-- /.row -->
    </div><!-- /.container -->
</div>
{% endblock %}}

mailing/templates/mailing/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Сайт каталог{% endblock %}</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Сайт каталог</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты</a>
                </li>
            </ul>
        </div>
    </nav>

<header>
    {% include 'includes/main_menu.html'%}
</header>

    <div class="container mt-5">

   {% block content %}{% endblock %}
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/contacts.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>

                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>WWW Ленинград</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="+7(ХХХ)ХХХ ХХ ХХ" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">Электронная почта</label>
                            <input type="text" name="email" class="form-control" id="email" placeholder="email@email.ru" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <a class="btn btn-dark" href="{% url 'mailing:message' %}" role="button">Отправить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}


<div class="row">
    <div class="col-12">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center mt-5">
            {% if user.is_authenticated %}
            <h2 class="row justify-content-center">Приветствуем Вас {{user.email}} на нашем сайте</h2>
            {% else %}
            <h2 class="row justify-content-center">Приветствуем Вас на нашем сайте , зарегистируйтесь чтобы видеть рассылки</h2>
            {% endif %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4 ">
        <ul class="list-group px-3 py-3 pt-md-5 pb-md-4 mx-auto ml-auto">
            {% if user.is_superuser %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:mailing_list' %}">Создано рассылок: </a>
                <span class="badge bg-dark rounded-pill">
                {{ count_mailing|default:"Нет данных" }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:mailing_list' %}">Количество активных рассылок: </a>
                <span class="badge bg-dark rounded-pill">
                <p>{{ active_mailings_count|default:"Нет данных" }}</p>
</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'mailing:receivemail_list' %}">Количество уникальных получателей: </a>
                <span class="badge bg-dark rounded-pill">
                    {{ unique_clients_count|default:"Нет данных" }}
                </span>
            </li>
            {% else %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Создано рассылок:
                <span class="badge bg-dark rounded-pill">{{ count_mailing }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Количество активных рассылок:
                <span class="badge bg-dark rounded-pill">{{ active_mailings_count }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Количество уникальных получателей:
                <span class="badge bg-dark rounded-pill">{{ unique_clients_count }}</span>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

mailing/templates/mailing/message.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <h1 class="mt-5">Главная страница</h1>
    <p class="lead"></p>
  </div>
  <div class="row mb-2">
    <div class="col-md-12">

        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <div class="row">
                <div class="col-6">
                    <form class="row" method="post" enctype="multipart/form-data">
                        <div class="card">
                            <p class="card-text">Ваше сообщение получено!</p>
                            <div class="card-body"></div>
                            <div class="row mb-2">
                            <div class="col-md-12">
                                <a class="btn btn-dark" href="{% url 'mailing:home' %}" role="button">Главная</a>
                                <a class="btn btn-dark" href="{% url 'mailing:contacts' %}" role="button">Контакты</a>
                            </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container marketing mt-5">
    <div class="row">

        <div class="col-lg-4">

            <p>Тема сообщения {{object.subject}}<p>
            <p>Текст сообщения {{object.content}}<p>
            <p><a class="btn btn-secondary" href="{% url 'mailing:message_list' %}">Назад</a></p>
        </div><!-- /.col-lg-4 -->

    </div><!-- /.row -->
</div><!-- /.container -->
{% endblock %}}

mailing/templates/mailing/receivemail_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container marketing mt-5">
    <div class="container text-center mt-3">
        <div class="row justify-content-center">
            <div class="col-4">

            </div>
            <div class="col-4">
                <h2>Получатели</h2>
                {% if user.is_authenticated %}
                <a class="btn btn-success mt-3" href="{% url 'mailing:receivemail_form' %}">Добавить получателя
                    &raquo;</a></p>
                {% endif %}
            </div>
            <div class="col-4">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="table-responsive small">
            <table class="table table-success table-striped">
                <thead>
                <tr>
                    <th>Фото</th>
                    <th>ФИО получателя</th>
                    <th>email получателя</th>
                    <th>Комментарий</th>
                    {% if request.user.is_superuser %}
                    <th>Создал</th>
                    {% endif %}
                    <th>Действия</th>
                </tr>
                </thead>

                {% for object in object_list %}
                <tr>
                    <td>
                        <img src="{{ object.avatar|media_filter }}" alt="Фото" class="rounded" width="40" height="40">

                    </td>
                    <td>{{ object.fio }}</td>
                    <td>{{ object.mail}}</td>
                    <td>{{ object.comment|truncatechars:30 }}</td>
                   {% if user.is_authenticated %}
                    <td>{{ object.owner }}</td>
                    {% endif %}
                    <td>
                        <a class="btn btn-primary btn-sm"
                           href="{% url 'mailing:receivemail_detail' object.pk%}">Посмотреть
                            &raquo;</a>
                        {% if user.owner %}
                        <a class="btn btn-primary btn-sm"
                           href="{% url 'mailing:receivemail_update' object.pk%}">Редактировать
                            &raquo;</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'mailing:receivemail_delete' object.pk%}">Удалить</a>
                        {% endif %}
                    </td>

                </tr>
                {% endfor%}
            </table>

        </div><!-- /.row -->

    </div><!-- /.row -->
</div><!-- /.container -->
{% endblock %}}

mailing/templates/mailing/send_list.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Управление сообщениями</h1>
    <p class="lead">Вы можете добавлять, просматривать, редактировать и удалять сообщения</p>
    <div class="container">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="btn btn-dark" href="{% url 'mailing:message_create' %}" role="button">Создать сообщение</a>
      </li>
    {% endif %}
    </div>
    <div class="row mb-2">
    <div class="col-md-12">
      {% for object in object_list %}
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">Тема сообщения: {{object.topic}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Содержание: {{object.content}}</strong>
          {% if user.is_authenticated or user.is_superuser%}
          <strong class="d-inline-block mb-2 text-primary-emphasis">Пользователь: {{object.owner}}</strong>

        </div>
        <div class="row mb-2">
        {% if user.is_authenticated%}
        <div class="col-md-12">
          <a class="btn btn-dark" href="{% url 'message:sms_detail' object.pk %}" role="button">Посмотреть</a>
          <a class="btn btn-dark" href="{% url 'message:sms_update' object.pk %}" role="button">Редактировать</a>
          {% endif %}
          {% if perms.message.delete_sms or sms.owner == object.user.email %}
            <a class="btn btn-dark" href="{% url 'message:sms_delete' object.pk %}" role="button">Удалить</a>
          {% endif %}
        </div>
        {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
    </div>
  </div>
</main>
{% endblock %}