config/urls.py
# flake8: noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings
from mailing import views
from mailing.views import homeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homeView.as_view(), name="home"),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
# flake8: noqa
from django.urls import include, path
from django.views.decorators.cache import cache_page
from . import views
from django.conf import settings
from django.conf.urls.static import static

from mailing.apps import MailingConfig
from mailing.services import block_mailing, run_mail
from mailing.views import (Contacts, MailingAttemptCreateView, MailingAttemptListView, MailingCreateView,
                           MailingDeleteView, MailingDetailView,
                           MailingListView, MailingUpdateView, MessageCreateView, MessageDeleteView,
                           MessageDetailView, MessageListView,
                           MessageUpdateView, ReceiveMailCreateView, ReceiveMailDetailView, ReceiveMailingDeleteView,
                           ReceiveMailListView,
                           ReceiveMailUpdateView, homeView, Messages)

app_name = MailingConfig.name

urlpatterns = [
    path("home/", homeView.as_view(), name="home"),
    path("contacts/", cache_page(60)(Contacts.as_view()), name="contacts"),
    path("message/", Messages.as_view(), name="message"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>/run_mail/", run_mail, name="run_mail"),
    path("mailing/<int:pk>/detail/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/new/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/edit/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("receivemail/", ReceiveMailListView.as_view(), name="receivemail_list"),
    path("receivemail/<int:pk>/detail/", cache_page(60)(ReceiveMailDetailView.as_view()), name="receivemail_detail"),
    path("receivemail/create/", ReceiveMailCreateView.as_view(), name="receivemail_form"),
    path("receivemail/<int:pk>/edit/", ReceiveMailUpdateView.as_view(), name="receivemail_update"),
    path("receivemail/<int:pk>/delete/", ReceiveMailingDeleteView.as_view(), name="receivemail_delete"),
    path("message/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/detail/", MessageDetailView.as_view(), name="message_detail"),
    path("message/new/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/edit/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("send/", MailingAttemptListView.as_view(), name="send_list"),
    path("send/create/", MailingAttemptCreateView.as_view(), name="send_create"),
    path("attempt/", MailingAttemptListView.as_view(), name="attempt"),
    path("block_mailing/<int:pk>", block_mailing, name="block_mailing"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UserListView,
    UserUpdateView,
    email_verification, PasswordRecoveryView, user_logout,
)
# flake8: noqa
app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", user_logout, name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("users/", UserListView.as_view(), name="user_list"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
    path("password-recovery/", PasswordRecoveryView.as_view(), name="password_recovery"),
    # path("attempt/", cache_page(60)(MailingAttemptListView.as_view()), name="attempt"),
]

users/models.py
# flake8: noqa
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(
        max_length=35, verbose_name="телофон", blank=True, null=True, help_text="введи номер телефона"
    )
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name="Фамилия")
    middle_name = models.CharField(max_length=50, verbose_name="Отчество", blank=True, null=True)
    avatar = models.ImageField(upload_to="photo/avatars/", blank=True, null=True, verbose_name="Аватар")
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name="Страна", help_text="Укажите страну")
    token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "Блокировка пользователя"),
        ]

    def __str__(self):
        return self.email

users/forms.py
# flake8: noqa
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, UserCreationForm
from django.forms import ModelForm
from django.urls import reverse_lazy
from django import forms
from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")




class UserUpdateForm(StyleFormMixin, ModelForm):

    class Meta:
        model = User
        fields = "__all__"
        exclude = ("token",)

        success_url = reverse_lazy("users:users")


class UserForgotPasswordForm(PasswordResetForm):
    """Форма запроса на восстановление пароля"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserSetNewPasswordForm(SetPasswordForm):
    """Форма изменения пароля пользователя после подтверждения"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class PasswordRecoveryForm(StyleFormMixin, forms.Form):
    email = forms.EmailField(label="Укажите Email")

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get("email")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такого email нет в системе")
        return email

users/views.py
import secrets

from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, TemplateView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserForgotPasswordForm, UserRegisterForm, UserSetNewPasswordForm, UserUpdateForm, \
    PasswordRecoveryForm
from users.models import User

# Create your views here.

def user_logout(request):
    logout(request)
    return render(request, template_name='mailing/home.html')

class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Потверждение почты",
            message=f"Рады вашей регистрации!Осталось потвердить почту!{url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return HttpResponse("подтвержден")


class UserListView(ListView):
    model = User
    template_name = "users/user_lists.html"
    context_object_name = "users_list"


class UserDetailView(DetailView):
    model = User
    form_class = UserUpdateForm


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm


class UserDeleteView(DeleteView):
    model = User
    form_class = UserUpdateForm


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """Представление установки нового пароля"""

    form_class = UserSetNewPasswordForm
    template_name = "users/user_password_set_new.html"
    success_url = reverse_lazy("users:login")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль"
        return context

# flake8: noqa
class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """Представление по сбросу пароля по почте"""

    form_class = UserForgotPasswordForm
    template_name = "users/password_reset.html"
    success_url = reverse_lazy("users:login")
    success_message = "Письмо с инструкцией по восстановлению пароля отправлено на ваш email"
    subject_template_name = "users/email/password_subject_reset_mail.txt"
    email_template_name = "users/email/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля"
        return context


class PasswordRecoveryView(FormView):
    template_name = "password_recovery.html"
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        user = User.objects.get(email=email)
        length = 12
        alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        password = get_random_string(length, alphabet)
        user.set_password(password)
        user.save()
        send_mail(
            subject="Восстановление пароля",
            message=f"Ваш новый пароль: {password}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return super().form_valid(form)

users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Удаление пользователя</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
        <div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Вы действительно хотите удалить пользователя: "{{object.email}}"</p>
                    <div class="card-body">
                        {%  csrf_token %}
                    </div>
                    <div class="row mb-2">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark">Удалить</button>
                        <a class="btn btn-dark" href="{% url 'users:user_list' %}" role="button">Отменить</a>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Пользователь</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">email: {{object.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Имя: {{object.first_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Фамилия: {{object.last_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Телефон: {{object.phone}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Страна: {{object.country}}</strong>
          <avatar class="d-inline-block mb-2 text-primary-emphasis">Аватар: {{object.country}}</avatar>

        </div>
        <div class="row mb-2">
        <div class="col-md-12">
          <a class="btn btn-dark" href="{% url 'users:user_list' %}" role="button">Назад</a>
        </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="form-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-primary mt-1" href="{% url 'mailing:mailing_list' %}" role="button">Отмена</a>


                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_lists.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Пользователи</h1>
    <div class="container">
    <div class="row mb-2">
    <div class="col-md-12">
    {% for object in object_list %}
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">email: {{object.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Имя: {{object.first_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Фамилия: {{object.last_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Активность: {{ object.is_active |yesno:"Активна, Не активна" }}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Телефон: {{object.phone}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Страна: {{object.country}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Аватар: {{object.country}}</strong>
        </div>

        <div class="row mb-2">
        <div class="col-md-12">
        {% if user.is_superuser %}
          <a class="btn btn-dark" href="{% url 'users:user_update' object.pk %}" role="button">Редактировать</a>
          <a class="btn btn-dark" href="{% url 'users:user_delete' object.pk %}" role="button">Удалить</a>
        {% endif %}
        </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}